require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BundlesController do

  # This should return the minimal set of attributes required to create a valid
  # Bundle. As you add validations to Bundle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all bundles as @bundles" do
      bundle = Bundle.create! valid_attributes
      get :index
      assigns(:bundles).should eq([bundle])
    end
  end

  describe "GET show" do
    it "assigns the requested bundle as @bundle" do
      bundle = Bundle.create! valid_attributes
      get :show, :id => bundle.id
      assigns(:bundle).should eq(bundle)
    end
  end

  describe "GET new" do
    it "assigns a new bundle as @bundle" do
      get :new
      assigns(:bundle).should be_a_new(Bundle)
    end
  end

  describe "GET edit" do
    it "assigns the requested bundle as @bundle" do
      bundle = Bundle.create! valid_attributes
      get :edit, :id => bundle.id
      assigns(:bundle).should eq(bundle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bundle" do
        expect {
          post :create, :bundle => valid_attributes
        }.to change(Bundle, :count).by(1)
      end

      it "assigns a newly created bundle as @bundle" do
        post :create, :bundle => valid_attributes
        assigns(:bundle).should be_a(Bundle)
        assigns(:bundle).should be_persisted
      end

      it "redirects to the created bundle" do
        post :create, :bundle => valid_attributes
        response.should redirect_to(Bundle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bundle as @bundle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bundle.any_instance.stub(:save).and_return(false)
        post :create, :bundle => {}
        assigns(:bundle).should be_a_new(Bundle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bundle.any_instance.stub(:save).and_return(false)
        post :create, :bundle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bundle" do
        bundle = Bundle.create! valid_attributes
        # Assuming there are no other bundles in the database, this
        # specifies that the Bundle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bundle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bundle.id, :bundle => {'these' => 'params'}
      end

      it "assigns the requested bundle as @bundle" do
        bundle = Bundle.create! valid_attributes
        put :update, :id => bundle.id, :bundle => valid_attributes
        assigns(:bundle).should eq(bundle)
      end

      it "redirects to the bundle" do
        bundle = Bundle.create! valid_attributes
        put :update, :id => bundle.id, :bundle => valid_attributes
        response.should redirect_to(bundle)
      end
    end

    describe "with invalid params" do
      it "assigns the bundle as @bundle" do
        bundle = Bundle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bundle.any_instance.stub(:save).and_return(false)
        put :update, :id => bundle.id, :bundle => {}
        assigns(:bundle).should eq(bundle)
      end

      it "re-renders the 'edit' template" do
        bundle = Bundle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bundle.any_instance.stub(:save).and_return(false)
        put :update, :id => bundle.id, :bundle => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bundle" do
      bundle = Bundle.create! valid_attributes
      expect {
        delete :destroy, :id => bundle.id
      }.to change(Bundle, :count).by(-1)
    end

    it "redirects to the bundles list" do
      bundle = Bundle.create! valid_attributes
      delete :destroy, :id => bundle.id
      response.should redirect_to(bundles_url)
    end
  end

end
